public class VariablesTheme {
    public static void main(String[] args) {
        System.out.println("\n1. Вывод характеристик компьютера: ");
        byte pcWeight = 15;
        System.out.println("Вес ПК: " + pcWeight + " Кг");
        short numberCpuCores = 24;
        System.out.println("Количество ядер процессора: " + numberCpuCores);
        int ram = 64;
        System.out.println("Объем оперативной памяти: " + ram + " Гб");
        long supplyUnitPower = 1000L;
        System.out.println("Мощность блока питания: " + supplyUnitPower + " Вт");
        float baseClockFrequency = 3.2F;
        System.out.println("Базовая тактовая частота: " + baseClockFrequency + " ГГц");
        double autoClockSpeedIncrease = 5.8;
        System.out.println("Увеличение тактовой частоты: " + autoClockSpeedIncrease + " ГГц");
        char typeVideoCard = 'D';
        System.out.println("Тип видеокарты " + typeVideoCard + " = дискретная");
        boolean freeSpaceHdd = true;
        System.out.println("Есть свободное место на диске? Ответ: " + freeSpaceHdd);

        System.out.println("\n2. Расчет стоимости товара со скидкой: ");
        int penPrice = 100;
        int bookPrice = 200;
        int discount = 11;
        int sumGoods = penPrice + bookPrice;
        int discountAmount = (sumGoods / 100) * discount;
        int discountPrice = sumGoods - discountAmount;
        System.out.println("Общая стоимость товаров без скидки: " + sumGoods + " руб.");
        System.out.println("Сумма скидки: " + discountAmount + " руб.");
        System.out.println("Общая стоимость товаров со скидкой: " + discountPrice + " руб.");

        System.out.println("\n3. Вывод слова JAVA: ");
        System.out.println("   J    a  v     v  a");
        System.out.println("   J   a a  v   v  a a");
        System.out.println("J  J  aaaaa  V V  aaaaa");
        System.out.println(" JJ  a     a  V  a     a");

        System.out.println("\n4. Вывод min и max значений целых числовых типов: ");
        byte byteMaxValue = Byte.MAX_VALUE;
        short shortMaxValue = Short.MAX_VALUE;
        int intMaxValue = Integer.MAX_VALUE;
        long longMaxValue = Long.MAX_VALUE;
        char charMaxValue = Character.MAX_VALUE;
        System.out.println("Первоначальное значение byte: " + byteMaxValue);
        System.out.println("Значение byte после инкремента на 1: " + ++byteMaxValue);
        System.out.println("Значение byte после декремента на 1: " + --byteMaxValue);
        System.out.println("Первоначальное значение short: " + shortMaxValue);
        System.out.println("Значение short после инкремента на 1: " + ++shortMaxValue);
        System.out.println("Значение short после декремента на 1: " + --shortMaxValue);
        System.out.println("Первоначальное значение int: " + intMaxValue);
        System.out.println("Значение int после инкремента на 1: " + ++intMaxValue);
        System.out.println("Значение int после декремента на 1: " + --intMaxValue);
        System.out.println("Первоначальное значение long: " + longMaxValue);
        System.out.println("Значение long после инкремента на 1: " + ++longMaxValue);
        System.out.println("Значение long после декремента на 1: " + --longMaxValue);
        System.out.println("Первоначальное значение char: " + charMaxValue);
        System.out.println("Значение char после инкремента на 1: " + ++charMaxValue);
        System.out.println("Значение char после декремента на 1: " + --charMaxValue);

        System.out.println("\n5. Перестановка значений переменных: ");
        int a = 5;
        int b = 2;
        System.out.println("Перестановка значений переменных с помощью третьей переменной");
        System.out.println("Исходные значения: a = " + a + " , b = " + b);
        int c = a;
        System.out.println("Новые значения: a = " + (a = (a = b)) + " , b = " + (b = (b = c)));
        System.out.println("Перестановка значений переменных с помощью арифметических операций");
        System.out.println("Исходные значения: a = " + a + " , b = " + b);
        System.out.println("Новые значения: a = " + (a = a + b - (b = a)) + " , b = " + b);
        System.out.println("Перестановка значений переменных с помощью побитовой операции");
        System.out.println("Исходные значения:");
        int c1 = a ^ b;
//      (((a) ^= (b)), ((b) ^= (a)), ((a) ^= (b))));
        System.out.println(a + " в двоичной системе исчисления: " + Integer.toBinaryString(a));
        System.out.println(b + " в двоичной системе исчисления: " + Integer.toBinaryString(b));
        System.out.println(c1 + " в двоичной системе исчисления: " + Integer.toBinaryString(c1));
        System.out.println("Новые значения: a = " + (a = (a = b)) + " , b = " + (b = (b = c1)));

        System.out.println("\n6. Вывод символов и их кодов: ");
        char dollar = '$';
        char asterisk = '*';
        char atSign = '@';
        char verticalBar = '|';
        char tilde = '~';
        System.out.printf("%d %d %d %d %d \n", 
                (int) (dollar), (int) asterisk, (int) atSign, (int) verticalBar, (int) tilde);
        System.out.printf("%s %s %s %s %s %n", dollar, asterisk, atSign, verticalBar, tilde);

        System.out.println("\n7. Вывод в консоль ASCII-арт Дюка: ");
        char slash = 47;
        char backslash = 92;
        char underscore = 95;
        char leftParenthesis = 40;
        char rightParenthesis = 41;
        char space = 32;
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(slash);
        System.out.println(backslash);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(slash);
        System.out.print(space);
        System.out.print(space);
        System.out.println(backslash);
        System.out.print(space);
        System.out.print(space);
        System.out.print(slash);
        System.out.print(underscore);
        System.out.print(leftParenthesis);
        System.out.print(space);
        System.out.print(rightParenthesis);
        System.out.println(backslash);
        System.out.print(space);
        System.out.print(slash);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.print(space);
        System.out.println(backslash);
        System.out.print(slash);
        System.out.print(underscore);
        System.out.print(underscore);
        System.out.print(underscore);
        System.out.print(underscore);
        System.out.print(slash);
        System.out.print(backslash);
        System.out.print(underscore);
        System.out.print(underscore);
        System.out.println(backslash);

        System.out.println("\n8. Вывод количества сотен, десятков и единиц числа: ");
        int numberN = 123;
        int hundreds = numberN / 100;
        int tens = (numberN / 10) % 10;
        int ones = numberN % 10;
        int sum = hundreds + tens + ones;
        int product = hundreds * tens * ones;
        System.out.println("Число " + numberN + " содержит:");
        System.out.println("Сотен - " + hundreds);
        System.out.println("Десятков - " + tens);
        System.out.println("Единиц - " + ones);
        System.out.println("Сумма его цифр = " + sum);
        System.out.println("Произведение = " + product);

        System.out.println("\n9. Вывод времени: ");
        int totalSecondsTime = 86399;
        int hh = totalSecondsTime / 3600;
        int mm = totalSecondsTime / 60 % 60;
        int ss = totalSecondsTime / 1 % 60;
        System.out.println("Время: " + ((hh) + ":" + (mm) + ":" + (ss)));
    }
}